name: Build itscaro/gitlab-utils:latest
on:
  push:
    branches:
    - master
jobs:
  build-latest:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker image itscaro/gitlab-utils:latest
      env:
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        DOCKER_HUB_LOGIN: ${{ secrets.DOCKER_HUB_LOGIN }}
      run: |
        docker build . --file Dockerfile --tag itscaro/gitlab-utils:latest
        echo "${DOCKER_HUB_TOKEN}" | docker login -u "${DOCKER_HUB_LOGIN}" --password-stdin
        docker push itscaro/gitlab-utils:latest
